export const CATEGORIAS = [
  "Panes",
  "Facturas",
  "Tortas",
  "Sandwiches",
  "Dulces",
  "Fiambres y Aceitunas",
  "Quesos",
  "Vinos",
  "Bebidas",
  "Yerba, Café y Mermeladas",
  "Limpieza",
  "Almacén Varios",
  "Lácteos",
  "Copetín",
  "Perfumería",
  "Varios",
  "Conservas",
  "Galletitas",
  "Golosinas",
  "Congelados, Leña y Mascotas",
  "Navidad",
  "Librería",
  "Cafetería",
  "Regalería",
  "Otros",
] as const;
