import {
  IconGrid,
  IconPackage,
  IconStorefront,
  IconUsers,
  IconTruckSupply,
  IconBoxes,
  IconCash,
  IconClipboardList,
  IconReceipt,
  IconChart,
  IconSettings,
  IconIdCard,
  IconWallet,
  IconFileText,
  IconHandshake,
  IconTag,
} from "@/components/admin-icons";

export const MODULOS_NAV = [
  { href: "/admin", label: "Inicio", icon: IconGrid, exact: true, modulo: null },
  { href: "/admin/productos", label: "Productos", icon: IconPackage, exact: false, modulo: "productos" },
  { href: "/admin/categorias", label: "Categorías", icon: IconTag, exact: false, modulo: "categorias" },
  { href: "/admin/sucursales", label: "Sucursales", icon: IconStorefront, exact: false, modulo: "sucursales" },
  { href: "/admin/personal", label: "Personal", icon: IconUsers, exact: false, modulo: "personal" },
  { href: "/admin/empleados", label: "Empleados", icon: IconIdCard, exact: false, modulo: "empleados" },
  { href: "/admin/proveedores", label: "Proveedores", icon: IconTruckSupply, exact: false, modulo: "proveedores" },
  { href: "/admin/stock", label: "Stock", icon: IconBoxes, exact: false, modulo: "stock" },
  { href: "/admin/pedidos", label: "Pedidos", icon: IconClipboardList, exact: false, modulo: "pedidos" },
  { href: "/admin/caja", label: "Caja", icon: IconCash, exact: false, modulo: "caja" },
  { href: "/admin/facturacion", label: "Facturación", icon: IconReceipt, exact: false, modulo: "facturacion" },
  { href: "/admin/gastos", label: "Gastos", icon: IconWallet, exact: false, modulo: "gastos" },
  { href: "/admin/contratos", label: "Contratos", icon: IconFileText, exact: false, modulo: "contratos" },
  { href: "/admin/clientes-cuenta-corriente", label: "Clientes CC", icon: IconHandshake, exact: false, modulo: "clientes_cc" },
  { href: "/admin/reportes", label: "Reportes", icon: IconChart, exact: false, modulo: "reportes" },
  { href: "/admin/configuracion", label: "Configuración", icon: IconSettings, exact: false, modulo: "configuracion" },
] as const;

export const BOTON_GRADIENTE: Record<string, string> = {
  productos: "from-amber-500 to-orange-600",
  categorias: "from-rose-400 to-orange-500",
  sucursales: "from-sky-500 to-blue-600",
  personal: "from-violet-500 to-purple-600",
  empleados: "from-fuchsia-500 to-pink-600",
  proveedores: "from-teal-500 to-emerald-600",
  stock: "from-lime-500 to-green-600",
  pedidos: "from-rose-500 to-red-600",
  caja: "from-yellow-500 to-amber-600",
  facturacion: "from-cyan-500 to-teal-600",
  gastos: "from-orange-500 to-red-600",
  contratos: "from-indigo-500 to-violet-600",
  clientes_cc: "from-pink-500 to-rose-600",
  reportes: "from-blue-500 to-indigo-600",
  configuracion: "from-zinc-500 to-zinc-700",
};
